# Generated by Django 2.2.12 on 2024-09-17 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='up_time',
            new_name='up_num',
        ),
    ]
